const actions = {
	CHANGE_IS_USER_SIGNED_IN: "CHANGE_IS_USER_SIGNED_IN",
	SET_USER: "SET_USER",
	CREATE_LIST: "CREATE_LIST",
	FETCH_LISTS: "FETCH_LISTS",
	DELETE_LIST: "DELETE_LIST"
};

export default actions;
